# Note: you need to be using OpenAI Python v0.27.0 for the code below to work
import openai
from dotenv import load_dotenv
load_dotenv()

import os
openai.api_key = os.getenv("OPENAI_API_KEY")
openai.Model.list()

response = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",

  messages=[
        # The system message helps set the behavior of the assistant. In the example above, the assistant was instructed with “You are a helpful assistant
        {"role": "system", "content": "You are a law assistant."},
        # The user messages help instruct the assistant. They can be generated by the end users of an application, or set by a developer as an instruction.
        {"role": "user", "content": "What type of companies can I set?"},
        # The assistant messages help store prior responses. They can also be written by a developer to help give examples of desired behavior
        {"role": "assistant", "content": "llc, corporation, partnership, etc."},
        {"role": "user", "content": "How to set up corporation?"}
    ]
)

print(response["choices"][0]["message"]["content"])
